### ISSUE TITLE
Panic observed: converting extensions.ReplicaSets with v1 coder instead of extensions coder.

### ISSUE THREAD

**Issue by ingvagabund** [ingvagabund/cluster-capacity#2]
```
E1122 20:10:14.453800      15 runtime.go:64] Observed a panic: &errors.errorString{s:"extensions.ReplicaSet is not suitable for converting to [\"v1\"]"} (extensions.ReplicaSet is not suitable for converting to ["v1"])
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
/usr/lib/golang/src/runtime/asm_amd64.s:479
/usr/lib/golang/src/runtime/panic.go:458
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/runtime/codec.go:74
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/pkg/framework/watch/watch.go:79
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/pkg/framework/restclient/restclient.go:574
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/pkg/framework/restclient/restclient.go:640
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:659
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache/listwatch.go:76
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache/listwatch.go:95
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:294
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:204
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:87
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:88
/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:49
/usr/lib/golang/src/runtime/asm_amd64.s:2086
panic: extensions.ReplicaSet is not suitable for converting to ["v1"] [recovered]
	panic: extensions.ReplicaSet is not suitable for converting to ["v1"]
goroutine 129 [running]:
panic(0x1813b20, 0xc4202e05e0)
	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
panic(0x1813b20, 0xc4202e05e0)
	/usr/lib/golang/src/runtime/panic.go:458 +0x243
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/runtime.EncodeOrDie(0x7f391aa986f8, 0xc42029c1b0, 0x2669380, 0xc4201da000, 0xc42029c1b0, 0x0)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/runtime/codec.go:74 +0xce
github.com/ingvagabund/cluster-capacity/pkg/framework/watch.(*WatchBuffer).EmitWatchEvent(0xc42000d5e0, 0x1a90004, 0x5, 0x2669380, 0xc4201da000, 0xc4202e05c0, 0x1)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/pkg/framework/watch/watch.go:79 +0xa7
github.com/ingvagabund/cluster-capacity/pkg/framework/restclient.(*RESTClient).createWatchReadCloser(0xc4201a4000, 0x1a9860a, 0xb, 0x267ee00, 0xc420136de0, 0x0, 0x0, 0x0)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/pkg/framework/restclient/restclient.go:574 +0x1386
github.com/ingvagabund/cluster-capacity/pkg/framework/restclient.(*RESTClient).Do(0xc4201a4000, 0xc4201e4000, 0x0, 0x42, 0x0)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/pkg/framework/restclient/restclient.go:640 +0x188d
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/restclient.(*Request).Watch(0xc4202f49c0, 0x0, 0x0, 0x0, 0x0)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/restclient/request.go:659 +0x1e3
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache.NewListWatchFromClient.func2(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420343598, ...)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache/listwatch.go:76 +0x1b6
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache.(*ListWatch).Watch(0xc420342840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache/listwatch.go:95 +0x5e
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc42035cd80, 0xc42022efc0, 0x0, 0x0)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:294 +0x5f9
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil.func1()
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:204 +0x33
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc42024a7c0)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:87 +0x5e
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc42024a7c0, 0x3b9aca00, 0x0, 0x1, 0xc42022efc0)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:88 +0xad
github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc42024a7c0, 0x3b9aca00, 0xc42022efc0)
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:49 +0x4d
created by github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil
	/home/jchaloup/Projects/kubernetes/src/github.com/ingvagabund/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:207 +0x1c4
```

**Comment by chengzhang1016** [comment]
I also hit this issue random

**Comment by ingvagabund** [comment]
This is reproducible everytime there is a RS in cluster and the CC is run in watch mode. E.g.

```sh
 k get rs
NAME       DESIRED   CURRENT   READY     AGE
frontend   3         3         3         2m
$ cc --podspec https://raw.githubusercontent.com/ingvagabund/cluster-capacity/master/examples/pod.yaml --period 1
```

**Comment by ingvagabund** [comment]
Fixed with https://github.com/ingvagabund/cluster-capacity/commit/76f2faee5f24263766eca94bf23fc59a255b011f
